[build]
# see app/demo-stm32h7-nucleo/app-h753.toml
target = "thumbv7em-none-eabihf"

[thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Ttask-rlink.x"]

[env]
HUBRIS_TARGET = "thumbv7em-none-eabihf"
